import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import TreeDataGrid from "@/components/TreeDataGrid";
import GithubLoginWrapper from "@/components/GithubLoginWrapper";
import CompareAndCommit from "@/components/CompareAndCommit";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Collaborative Decision Matrix </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <GithubLoginWrapper />


        <div className={styles.grid}>
          <TreeDataGrid/>
          <CompareAndCommit />
        </div>
      </main>
    </>
  )
}
